type: "GestureRecognizer2"

################################################################################
# Inputs
################################################################################

input_stream: "LANDMARKS:landmarks"

# input_stream: "WORLD_LANDMARKS:multi_hand_world_landmarks"

# input_stream: "HANDEDNESS:multi_handedness"

input_stream: "ADD_GESTURE:add_gesture"

input_stream: "IS_RECORDING:is_recording"

################################################################################
# Outputs
################################################################################

output_stream: "GESTURE:recognized_gestures"
output_stream: "ACT_GESTURE:actionable_gestures"
output_stream: "REC_GESTURE:recorded_gestures"

################################################################################
# Graph
################################################################################


node {
    calculator: "LandmarkToGestureFrameCalculator"
    input_stream: "LANDMARKS:landmarks"
    output_stream: "FRAME:gesture_frames"
}

node {
    calculator: "DedupFramesCalculator"
    input_stream: "gesture_frames"
    output_stream: "dedupped_gesture_frames"
}

node {
    calculator: "PacketSequencerCalculator"
    input_stream: "INPUT:add_gesture"
    input_stream: "TICK:dedupped_gesture_frames"
    output_stream: "OUTPUT:synced_add_gesture"
}

node {
    calculator: "PacketSequencerCalculator"
    input_stream: "INPUT:is_recording"
    input_stream: "TICK:dedupped_gesture_frames"
    output_stream: "OUTPUT:synced_is_recording"
}

node {
    calculator: "PacketClonerCalculator"
    input_stream: "TICK:dedupped_gesture_frames"
    input_stream: "synced_is_recording"
    output_stream: "cloned_is_recording"
}

# node {
#     calculator: "EchoerCalculator"
#     input_stream: "cloned_is_recording"
# }

node {
    calculator: "GestureRecognizerCalculator"
    input_stream: "FRAME:dedupped_gesture_frames"
    input_stream: "GESTURE:synced_add_gesture"
    output_stream: "SEEN:recognized_gestures"
}

node {
    calculator: "GateCalculator"
    input_stream: "DISALLOW:cloned_is_recording"
    input_stream: "recognized_gestures"
    output_stream: "actionable_gestures"
}

# node {
#     calculator: "EchoerCalculator"
#     input_stream: "cloned_is_recording"
# }

# node {
#     calculator: "EchoerCalculator"
#     input_stream: "cloned_is_recording"
# }

node {
    calculator: "GateCalculator"
    input_stream: "ALLOW:cloned_is_recording"
    input_stream: "dedupped_gesture_frames"
    output_stream: "STATE_CHANGE:recording_changed"
    output_stream: "recordable_gesture_frames"
}

# node {
#     calculator: "EchoerCalculator"
#     input_stream: "recordable_gesture_frames"
# }

node {
    calculator: "GestureRecorderCalculator"
    input_stream: "FRAME:recordable_gesture_frames"
    input_stream: "FINISH:recording_changed"
    output_stream: "GESTURE:recorded_gestures"
}