# A graph implementing the JesturePipe pipeline

################################################################################
# Input Packets
################################################################################

input_stream: "GESTURE:gesture"

################################################################################
# Graph
################################################################################

node {
    calculator: "ActionsCalculator"
    input_stream: "GESTURE:gesture"
}