type: "Actions"

################################################################################
# Side Packets
################################################################################

input_side_packet: "ACTION_MAPPER:action_mapper"

################################################################################
# Streams
################################################################################

input_stream: "GESTURE_ID:gesture_id"

################################################################################
# Nodes
################################################################################

node {
    calculator: "ActionDispatcherCalculator"
    input_side_packet: "MAPPER:action_mapper"
    input_stream: "GESTURE_ID:gesture_id"
}