# load(":models.bzl", "model_to_bin")

package(default_visibility = ["//visibility:public"])

# model_to_bin(
#     name = "hand_landmark_lite",
#     model = "@mediapipe//mediapipe/modules/hand_landmark:hand_landmark_full.tflite",
#     var_name = "HAND_LANDMARK_LITE_MODEL_DATA",
# )
