
type: "HandGraph"


################################################################################
## Inputs
################################################################################

# Video frames (ImageFrame)
input_stream: "IMAGE:input_video",

################################################################################
## Outputs
################################################################################

# Video frames (ImageFrame)
output_stream: "IMAGE:output_video",

node {
    calculator: "ConstantSidePacketCalculator"
    output_side_packet: "PACKET:num_hands"
    node_options: {
        [type.googleapis.com/mediapipe.ConstantSidePacketCalculatorOptions] {
            packet { int_value: 2 }
        }
    }
}

node {
    calculator: "HandTrackingGraph"
    input_side_packet: "NUM_HANDS:num_hands"
    input_stream: "IMAGE:input_video"
    output_stream: "LANDMARKS:landmarks"
    output_stream: "HANDEDNESS:handedness"
    output_stream: "PALM_DETECTIONS:multi_palm_detections"
    output_stream: "HAND_ROIS_FROM_LANDMARKS:multi_hand_rects"
    output_stream: "HAND_ROIS_FROM_PALM_DETECTIONS:multi_palm_rects"
}

node {
  calculator: "HandRendererSubgraph"
  input_stream: "IMAGE:input_video"
  input_stream: "DETECTIONS:multi_palm_detections"
  input_stream: "LANDMARKS:landmarks"
  input_stream: "HANDEDNESS:handedness"
  input_stream: "NORM_RECTS:0:multi_palm_rects"
  input_stream: "NORM_RECTS:1:multi_hand_rects"
  output_stream: "IMAGE:output_video"
}
