# A graph implementing the JesturePipe pipeline

################################################################################
# Outputs
################################################################################

output_stream: "ANNOTATED_FRAME:annotated_frame"

################################################################################
# Graph
################################################################################

node {
    calculator: "CameraCalculator",
    output_stream: "VIDEO:annotated_frame",
}