# A graph implementing the JesturePipe pipeline

################################################################################
# Input Side Packets
################################################################################

input_side_packet: "CAMERA:camera_index"

################################################################################
# Outputs
################################################################################

output_stream: "ANNOTATED_FRAME:annotated_frame"

################################################################################
# Graph
################################################################################

node {
    calculator: "CameraCalculator",
    input_side_packet: "CAMERA:camera_index",
    output_stream: "VIDEO:annotated_frame",
}