package(default_visibility = ["//visibility:public"])

cc_library(
    name = "actions_calculator",
    srcs = ["actions_calculator.cc"],
    deps = [
        # "//jesturepipe/graphs/gesture_recognizer/calculators:gesture",
        "@actions//actions",
        "@actions//actions:action",
        "@com_google_absl//absl/status",
        "@mediapipe//mediapipe/framework:calculator_framework",
    ],
    alwayslink = 1,
)
