type: "GestureRecognizer"

################################################################################
# Inputs
################################################################################

input_stream: "LANDMARKS:multi_hand_landmarks"
